#ifndef FELIX_H
#define FELIX_H

/* Generated by cbindgen from crates/sdk/felix-capi. Do not edit; run `task capi:header`. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// A connection to a Felix cluster, with the runtime that drives it.
//
// Safe to use from several threads at once. Free it with
// `felix_client_free` after every subscription made from it is freed or
// abandoned; a subscription keeps the runtime alive on its own.
typedef struct FelixClient FelixClient;

// One record delivered to a subscription. Owns its payload until freed with
// `felix_event_free`.
typedef struct FelixEvent FelixEvent;

// A live subscription to one shard of a stream.
//
// It follows the shard to whichever broker owns it, as the Rust client
// does. Poll it from one thread at a time; concurrent polls take turns.
typedef struct FelixSubscription FelixSubscription;

// The result of every fallible call. `FELIX_STATUS_OK` is zero; every other
// value says why the call did not do what it was asked.
typedef int32_t FelixStatus;

// What the broker must have done before a publish returns.
typedef int32_t FelixAckMode;

// Where a subscription starts reading.
typedef int32_t FelixStartKind;

// Fire and forget: return once the record is sent.
#define FELIX_ACK_NONE 0

// Wait for the broker to acknowledge this record.
#define FELIX_ACK_PER_MESSAGE 1

// Wait for the broker to acknowledge the batch the record went out in.
#define FELIX_ACK_PER_BATCH 2

// The call did what it was asked.
#define FELIX_STATUS_OK 0

// A bounded wait ended with nothing to return. The handle is still usable.
#define FELIX_STATUS_TIMEOUT 1

// The broker ended the subscription. No more events will arrive on it.
#define FELIX_STATUS_CLOSED 2

// A required pointer was null, a string was not UTF-8, or a value was out
// of range. Nothing was sent.
#define FELIX_STATUS_INVALID_ARGUMENT 10

// The library panicked. The call did not complete; the handle may still be
// usable, but the failure is a bug worth reporting.
#define FELIX_STATUS_PANIC 11

// A failure with no more specific class.
#define FELIX_STATUS_ERROR 20

// The broker could not be reached, the connection was lost mid-call, or the
// broker is shutting down. Worth retrying.
#define FELIX_STATUS_CONNECTION 21

// The token was rejected or lacks the permission the call needs. Retrying
// will not help.
#define FELIX_STATUS_AUTH 22

// The tenant, namespace, stream or cache does not exist.
#define FELIX_STATUS_NOT_FOUND 23

// The requested start offset is no longer retained.
#define FELIX_STATUS_CURSOR 24

// No broker can serve the shard right now, usually while it moves. Nothing
// was applied; retrying is safe.
#define FELIX_STATUS_SHARD_UNAVAILABLE 25

// The broker is shedding load. Nothing was applied; retry after a pause.
#define FELIX_STATUS_OVERLOADED 26

// The write may or may not have been applied. Resend only if it is
// idempotent.
#define FELIX_STATUS_OUTCOME_UNKNOWN 27

// Only records published after the subscription is made.
#define FELIX_START_LATEST 0

// The oldest record the stream still retains.
#define FELIX_START_EARLIEST 1

// The record at `start_offset`: the first one the caller has not seen, so a
// resuming caller passes the offset it last handled plus one.
#define FELIX_START_OFFSET 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Connect to a Felix cluster.
//
// `addrs` is one `host:port`, or several separated by commas; any reachable
// one is enough and the rest are discovered. `tenant_id` and `token` are the
// credentials. `server_name` is the name the broker certificate must carry,
// `"localhost"` when null. `ca_file` is a PEM file of CA certificates to
// trust; when null the operating system's trust store is used.
//
// On success `*out_client` holds a client to free with `felix_client_free`.
//
// # Safety
//
// Every string is null or NUL-terminated, and `out_client` points to
// writable storage for one pointer.
FelixStatus felix_client_connect(const char *addrs,
                                 const char *tenant_id,
                                 const char *token,
                                 const char *server_name,
                                 const char *ca_file,
                                 struct FelixClient **out_client);

// Free a client. Null is ignored.
//
// Waits briefly for the client's background tasks to stop. Subscriptions
// made from it keep working until they are freed.
//
// # Safety
//
// `client` is null or a pointer from `felix_client_connect` that has not
// been freed, and no other thread is using it.
void felix_client_free(struct FelixClient *client);

// Publish one record to shard 0 of a stream.
//
// `payload` may be null when `payload_len` is zero. `ack` is one of the
// `FELIX_ACK_*` values.
//
// On success, `*out_has_offset` says whether the broker reported the
// record's log offset, and `*out_offset` holds it when it did. There is no
// offset when `ack` is `FELIX_ACK_NONE`, the stream has no log, or the
// broker acknowledged before writing. Either out-pointer may be null.
//
// # Safety
//
// `client` is a live client. The strings are null or NUL-terminated.
// `payload` is null or valid for `payload_len` bytes. The out-pointers are
// null or writable.
FelixStatus felix_client_publish(const struct FelixClient *client,
                                 const char *tenant_id,
                                 const char *ns,
                                 const char *stream,
                                 const uint8_t *payload,
                                 size_t payload_len,
                                 FelixAckMode ack,
                                 uint64_t *out_offset,
                                 bool *out_has_offset);

// The message for the last call on this thread that did not return
// `FELIX_STATUS_OK`, or null if that call succeeded.
//
// The string is owned by the library and stays valid until the next Felix
// call on the same thread. Copy it to keep it. Do not free it.
const char *felix_last_error_message(void);

// The record's bytes, exactly as published.
//
// `*out_data` stays valid until the event is freed. It may be null when
// `*out_len` is zero.
//
// # Safety
//
// `event` is a live event, and both out-pointers are writable.
FelixStatus felix_event_payload(const struct FelixEvent *event,
                                const uint8_t **out_data,
                                size_t *out_len);

// The record's log offset.
//
// `*out_has_offset` is false on a stream without a log, and from a broker
// that did not negotiate offsets. Either out-pointer may be null.
//
// # Safety
//
// `event` is a live event, and the out-pointers are null or writable.
FelixStatus felix_event_offset(const struct FelixEvent *event,
                               uint64_t *out_offset,
                               bool *out_has_offset);

// How many offsets just before this one hold no event, such as a new
// leader's generation-start record. A larger jump between consecutive
// offsets than this explains is a drop.
//
// # Safety
//
// `event` is a live event, and `out_skipped` is writable.
FelixStatus felix_event_skipped_before(const struct FelixEvent *event, uint64_t *out_skipped);

// Free an event and its payload. Null is ignored.
//
// # Safety
//
// `event` is null or a pointer from `felix_subscription_next_event` that has
// not been freed.
void felix_event_free(struct FelixEvent *event);

// Subscribe to shard 0 of a stream.
//
// `start` is one of the `FELIX_START_*` values; `start_offset` is read only
// for `FELIX_START_OFFSET`. On success `*out_subscription` holds a
// subscription to free with `felix_subscription_free`.
//
// # Safety
//
// `client` is a live client, the strings are null or NUL-terminated, and
// `out_subscription` points to writable storage for one pointer.
FelixStatus felix_client_subscribe(const struct FelixClient *client,
                                   const char *tenant_id,
                                   const char *ns,
                                   const char *stream,
                                   FelixStartKind start,
                                   uint64_t start_offset,
                                   struct FelixSubscription **out_subscription);

// Wait for the next event.
//
// Returns `FELIX_STATUS_OK` with `*out_event` set to an event to free with
// `felix_event_free`; `FELIX_STATUS_TIMEOUT` when `timeout_ms` passed with
// nothing (the subscription stays usable); or `FELIX_STATUS_CLOSED` once the
// broker has ended the stream. `*out_event` is null for anything but OK.
//
// A negative `timeout_ms` waits indefinitely; zero only takes an event that
// is already waiting.
//
// # Safety
//
// `subscription` is a live subscription, and `out_event` points to writable
// storage for one pointer.
FelixStatus felix_subscription_next_event(const struct FelixSubscription *subscription,
                                          int64_t timeout_ms,
                                          struct FelixEvent **out_event);

// Free a subscription, which stops it. Null is ignored.
//
// # Safety
//
// `subscription` is null or a pointer from `felix_client_subscribe` that
// has not been freed, and no other thread is using it.
void felix_subscription_free(struct FelixSubscription *subscription);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FELIX_H */
